export const CAR_FEATURES = [
    "GPS navigation system",
    "Bluetooth connectivity",
    "Backup camera",
    "Leather seats",
    "Heated steering wheel",
    "Keyless entry",
    "Cruise control",
    "Lane departure warning",
    "Automatic emergency braking",
    "Adaptive cruise control",
    "Blind-spot monitoring",
    "Apple CarPlay",
    "Android Auto",
    "Wireless charging",
    "Parking sensors",
    "Sunroof",
    "LED headlights",
    "Dual-zone climate control",
    "Power-adjustable seats",
    "Rain-sensing wipers",
    "Collision avoidance system",
    "Remote start",
    "Power liftgate",
    "Third-row seating",
    "Towing package",
    "Smartphone integration",
    "Voice recognition",
    "Wi-Fi hotspot",
    "HD radio",
    "USB ports",
    "360-degree camera",
    "Electric or hybrid option",
    "Lane-keeping assist",
    "Rear cross-traffic alert",
    "Multi-zone audio",
    "Driver memory settings",
    "Adjustable suspension",
    "Heated and ventilated seats",
    "Automatic parallel parking",
    "Traffic sign recognition",
    "Panoramic sunroof",
    "Built-in vacuum cleaner",
    "Hands-free tailgate",
    "Ambient interior lighting",
    "Gesture control",
    "Driver drowsiness detection",
    "In-car entertainment system",
    "Collision preparation system",
    "Driver assistance package"
  ]
  